<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 引入父依赖 ———— tbfirst-parent -->
    <parent>
        <groupId>com.tbfirst</groupId>
        <artifactId>tbfirst</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>tbfirst-common</artifactId>
    <packaging>pom</packaging>          <!-- 聚合BOM模块，打包类型为 pom -->
    <name>tbfirst-common</name>
    <description>tbfirst 微服务公共库聚合模块</description>

    <modules>
        <!--  通用响应体、异常、常量、工具类模块    -->
        <module>tbfirst-common-core</module>
        <!--  全局异常处理 / MVC 配置 / CORS / 参数校验模块    -->
        <module>tbfirst-common-web</module>
        <!--   JWT 工具、用户上下文、鉴权过滤器等安全相关模块     -->
        <module>tbfirst-common-security</module>
        <!--   Redis 配置相关模块     -->
        <module>tbfirst-common-redis</module>
        <!--   JJPA BaseEntity、审计、Flyway 复用配置模块     -->
        <module>tbfirst-common-datasource</module>
        <!--   Feign 配置模块     -->
        <module>tbfirst-common-feign</module>
        <!--   MDC TraceId 过滤器、Logstash JSON 编码器模块     -->
        <module>tbfirst-common-log</module>
        <!--   对象存储模块     -->
        <module>tbfirst-common-oss</module>
    </modules>
</project>
